name: Javier Guzman
job: Software Engineer
email: contact+portfolio@guzman.dev
show_downloads: false
google_analytics: G-F9ZEC3PHB0
linkedin: https://www.linkedin.com/in/javierguzmanjimenez/
twitter: https://twitter.com/javierguzmandev
github: https://github.com/javierguzman
cv_file: assets/files/cv.pdf
avatar: assets/images/avatar.jpg
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Here you can find how to contact me directly or through social media as well as my portfolio