name: Javier Guzman
job: Software Engineer
email: contact+guzmandev@guzman.dev
show_downloads: false
google_analytics:
linkedin: www.linkedin.com
twitter: www.twitter.com
github: www.github.com
cv: assets/files/cv.pdf
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Here you can find how to contact me directly or through social media as well as my portfolio